version: "2"
services:
  webserver:
      build:
        context: .
        args:
          MOODLE_LINK: ${MPDK_MOODLE_LINK}
          PHP_VERSION: ${MPDK_PHP_VERSION}
          XDEBUG_VERSION: ${MPDK_XDEBUG_VERSION}
          PYTHON_VERSION: ${MPDK_PYTHON_VERSION}
      depends_on:
      - db
      image: moodle-php-apache-dev:${MPDK_PHP_VERSION}_${MPDK_MOODLE_VERSION}_${MPDK_VERSION}
      environment:
        MOODLE_DOCKER_DBNAME: moodle
        MOODLE_DOCKER_DBUSER: moodle
        MOODLE_DOCKER_DBPASS: "moodle"
        MOODLE_DOCKER_BROWSER: firefox
        MOODLE_DOCKER_WEB_HOST: "${MOODLE_DOCKER_WEB_HOST}"
        COMPOSE_PROJECT_NAME: "${COMPOSE_PROJECT_NAME}"
      volumes:
        - "${MPDK_DATADIR}/mpdk-assets/config.docker-template.php:/var/www/html/config.php"
        - "${MPDK_BASEDIR}/plugin:/opt/mpdk/myplugins"
        - "${ASSETDIR}/web/apache2_faildumps.conf:/etc/apache2/conf-enabled/apache2_faildumps.conf"
  db:
    environment:
      POSTGRES_PASSWORD: "moodle"
  exttests:
    image: moodlehq/moodle-exttests
    volumes:
      - "${ASSETDIR}/exttests/apache2_ports.conf:/etc/apache2/ports.conf"
      - "${ASSETDIR}/exttests/apache2.conf:/etc/apache2/sites-enabled/000-default.conf"
  selenium:
    image: "selenium/standalone-firefox${MOODLE_DOCKER_SELENIUM_SUFFIX:-}:${MOODLE_DOCKER_BROWSER_TAG}"
#    volumes:
#      - "${MOODLE_DOCKER_WWWROOT}:/var/www/html:ro"