version: "2"
services:
  webserver:
      build:
        context: .
        args:
          MOODLE_LINK: ${MOODLE_DOCKER_LINK}
          MPDK_PHP_VERSION: ${MOODLE_DOCKER_PHP_VERSION}
      depends_on:
      - db
      image: moodle-php-apache-python-node:${MOODLE_DOCKER_PHP_VERSION}_${MOODLE_DOCKER_VERSION}
      environment:
        environment:
        MOODLE_DOCKER_DBNAME: moodle
        MOODLE_DOCKER_DBUSER: moodle
        MOODLE_DOCKER_DBPASS: "moodle"
        MOODLE_DOCKER_BROWSER: firefox
        MOODLE_DOCKER_WEB_HOST: "${MOODLE_DOCKER_WEB_HOST}"
      volumes:
        - "${IROOT}/config.php:/var/www/html/config.php"
        - "${MPDK_ROOT}/plugin:/opt/mpdk/myplugins"
        - "${ASSETDIR}/web/apache2_faildumps.conf:/etc/apache2/conf-enabled/apache2_faildumps.conf"
  db:
    environment:
      POSTGRES_PASSWORD: "moodle"
  exttests:
    image: moodlehq/moodle-exttests
    volumes:
      - "${ASSETDIR}/exttests/apache2_ports.conf:/etc/apache2/ports.conf"
      - "${ASSETDIR}/exttests/apache2.conf:/etc/apache2/sites-enabled/000-default.conf"
  selenium:
    image: "selenium/standalone-firefox${MOODLE_DOCKER_SELENIUM_SUFFIX:-}:${MOODLE_DOCKER_BROWSER_TAG}"
    volumes:
      - "${MOODLE_DOCKER_WWWROOT}:/var/www/html:ro"